import { notFound } from "next/navigation";
import { DataView } from "@/components/modules/data-view";
import { moduleDefinitions } from "@/services/module-services";
import type { ModuleKey } from "@/permissions/permission-matrix";
import { SuperAdminPage } from "@/components/super-admin/page";
import { SuperAdminAccount } from "@/components/super-admin/account";
import { AdminDashboard } from "@/components/admin/dashboard";
import { AdminContacts } from "@/components/admin/contacts";
import { TeamManagement } from "@/components/admin/team-management";
import { AdminCampaigns } from "@/components/admin/campaigns";
import { AdminTasks } from "@/components/admin/tasks";
import { AdminAudiences } from "@/components/admin/audiences";
import { AdminSocialPublisher } from "@/components/admin/social-publisher";
import { AdminAnalytics } from "@/components/admin/analytics";
import { AdminAutomations } from "@/components/admin/automations";
import { AdminForms } from "@/components/admin/forms";
import { UserCampaigns, UserContentStudio, UserDashboard, UserPerformance, UserTasks, UserTemplates } from "@/components/user/workspace";
import { UserAssetLibrary } from "@/components/user/asset-library";
const superSections = new Set(["dashboard","admins","billing","analytics","ai-credits","account"]);
export default async function ModulePage({ params }: { params: Promise<{role:string;section:string}> }) { const {role,section}=await params; if(role==="super-admin"&&superSections.has(section))return <SuperAdminPage section={section}/>; if(role==="admin"&&section==="dashboard")return <AdminDashboard/>; if(role==="admin"&&section==="users")return <TeamManagement/>; if(role==="admin"&&(section==="contacts"||section==="customers"))return <AdminContacts/>; if(role==="admin"&&section==="audiences")return <AdminAudiences/>; if(role==="admin"&&section==="tasks")return <AdminTasks/>; if(role==="admin"&&section==="forms")return <AdminForms/>; if(role==="admin"&&section==="campaigns")return <AdminCampaigns/>; if(role==="admin"&&section==="channels")return <AdminSocialPublisher/>; if(role==="admin"&&section==="analytics")return <AdminAnalytics/>; if(role==="admin"&&section==="account")return <SuperAdminAccount/>; if(role==="admin"&&section==="automations")return <AdminAutomations/>; if(role==="user"&&section==="dashboard")return <UserDashboard/>; if(role==="user"&&section==="tasks")return <UserTasks/>; if(role==="user"&&section==="campaigns")return <UserCampaigns/>; if(role==="user"&&section==="templates")return <UserTemplates/>; if(role==="user"&&section==="performance")return <UserPerformance/>; if(role==="user"&&section==="content")return <UserContentStudio/>; if(role==="user"&&section==="assets")return <UserAssetLibrary/>; if(role==="user"&&section==="account")return <SuperAdminAccount/>; if(!(section in moduleDefinitions))notFound(); return <DataView module={section as ModuleKey}/>; }
