# Generated by Django 6.0.6 on 2026-08-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0020_alter_template_subject_to_textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='provider_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
