# Generated by Django 6.0.6 on 2026-08-17 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0021_template_provider_data'),
        ('content_studio', '0005_brandvoice_brand_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='generated_content',
        ),
        migrations.AddField(
            model_name='template',
            name='content_draft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_templates', to='content_studio.contentdraft'),
        ),
    ]
