# Generated by Django 6.0.6 on 2026-09-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0022_remove_template_generated_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrecord',
            name='routing_logs',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
