# Generated by Django 6.0.6 on 2026-09-25 10:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0025_campaign_audience'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='task',
        ),
        migrations.AlterField(
            model_name='campaignaudience',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='campaigns.customerrecord'),
        ),
        migrations.AlterField(
            model_name='campaigndelivery',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='campaigns.customerrecord'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('first_name', models.CharField(blank=True, default='', max_length=150)),
                ('last_name', models.CharField(blank=True, default='', max_length=150)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('source', models.CharField(choices=[('imported', 'CSV Import'), ('form', 'Form Submission'), ('meta', 'Meta Ad Lead'), ('manual', 'Manual Entry'), ('api', 'API / Integration')], db_index=True, default='manual', max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Unsubscribed', 'Unsubscribed'), ('Bounced', 'Bounced'), ('Archived', 'Archived')], db_index=True, default='Active', max_length=20)),
                ('score', models.IntegerField(default=50)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initial_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='campaigns.customerupload')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contacts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='campaignaudience',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='campaigns.contact'),
        ),
        migrations.AddField(
            model_name='campaigndelivery',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='campaigns.contact'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['owner', 'email'], name='contacts_owner_i_6693cc_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['owner', 'phone'], name='contacts_owner_i_54516d_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['status'], name='contacts_status_f623d1_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['source'], name='contacts_source_e764ce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('owner', 'email')},
        ),
    ]
