# Generated by Django 6.0.6 on 2026-09-28 06:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0027_alter_contact_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='sub_source_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contact',
            name='sub_source_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contact',
            name='sub_source_type',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['sub_source_type', 'sub_source_id'], name='contacts_sub_sou_22a0a8_idx'),
        ),
    ]
