# Generated by Django 6.0.6 on 2026-08-17 12:17

from django.db import migrations, models


def migrate_data(apps, schema_editor):
    GeneratedContent = apps.get_model('content_studio', 'GeneratedContent')
    ContentVersion = apps.get_model('content_studio', 'ContentVersion')
    Caption = apps.get_model('content_studio', 'Caption')
    
    ContentDraft = apps.get_model('content_studio', 'ContentDraft')
    ContentDraftVersion = apps.get_model('content_studio', 'ContentDraftVersion')
    ContentPlatform = apps.get_model('content_studio', 'ContentPlatform')

    # Migrate GeneratedContent to ContentDraft
    for gc in GeneratedContent.objects.all():
        draft = ContentDraft.objects.create(
            owner=gc.created_by,
            content_type=gc.content_type,
            workflow_state=gc.status, 
            original_prompt="",
            current_version=0
        )
        
        for cv in ContentVersion.objects.filter(generated_content=gc).order_by('version_number'):
            draft.current_version = cv.version_number
            if draft.original_prompt == "":
                draft.original_prompt = cv.prompt
            ContentDraftVersion.objects.create(
                draft=draft,
                version_number=cv.version_number,
                text_content=cv.text_content,
                image_url=cv.image_url,
                created_by=gc.created_by
            )
        draft.save()

        if gc.platform != "NONE":
            ContentPlatform.objects.create(
                draft=draft,
                platform=gc.platform,
                status="PENDING" 
            )

    # Migrate Caption to ContentPlatform
    for cap in Caption.objects.all():
        cp = cap.platform
        cp.caption_text = cap.caption_text
        cp.hashtags = cap.hashtags
        cp.cta = cap.cta
        cp.is_manually_edited = cap.is_manually_edited
        cp.save()

class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0022_remove_template_generated_content_and_more'),
        ('content_studio', '0005_brandvoice_brand_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentdraft',
            name='content_type',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('BLOG', 'Blog'), ('AD_COPY', 'Ad Copy'), ('SOCIAL', 'Social Media'), ('CAPTION', 'Caption')], db_index=True, default='SOCIAL', max_length=20),
        ),
        migrations.AddField(
            model_name='contentdraftversion',
            name='image_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='contentdraftversion',
            name='text_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentplatform',
            name='caption_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contentplatform',
            name='cta',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contentplatform',
            name='hashtags',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contentplatform',
            name='is_manually_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(migrate_data),
        migrations.RemoveField(
            model_name='contentversion',
            name='generated_content',
        ),
        migrations.RemoveField(
            model_name='generatedcontent',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Caption',
        ),
        migrations.DeleteModel(
            name='ContentVersion',
        ),
        migrations.DeleteModel(
            name='GeneratedContent',
        ),
    ]
