# Generated by Django 6.0.6 on 2026-10-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_studio', '0006_alter_contentversion_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentplatform',
            name='first_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contentplatform',
            name='location_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
