# Generated by Django 6.0.6 on 2026-08-17 16:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_websiteevent_website_eve_organiz_d63e22_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('WEBSITE', 'Website'), ('WEBHOOK', 'Webhook'), ('SYSTEM', 'System')], db_index=True, default='WEBSITE', max_length=20)),
                ('event_name', models.CharField(blank=True, db_index=True, max_length=100)),
                ('user_identifier', models.CharField(blank=True, db_index=True, max_length=255)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('url', models.CharField(blank=True, max_length=2048)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'system_event',
            },
        ),
        migrations.RemoveIndex(
            model_name='websiteevent',
            name='website_eve_created_0332c1_idx',
        ),
        migrations.RemoveIndex(
            model_name='websiteevent',
            name='website_eve_event_n_072942_idx',
        ),
        migrations.RemoveIndex(
            model_name='websiteevent',
            name='website_eve_user_id_54e06b_idx',
        ),
        migrations.DeleteModel(
            name='WebsiteEvent',
        ),
        migrations.AddIndex(
            model_name='systemevent',
            index=models.Index(fields=['event_type'], name='system_even_event_t_3724d9_idx'),
        ),
        migrations.AddIndex(
            model_name='systemevent',
            index=models.Index(fields=['event_name'], name='system_even_event_n_33876c_idx'),
        ),
        migrations.AddIndex(
            model_name='systemevent',
            index=models.Index(fields=['user_identifier'], name='system_even_user_id_6dadde_idx'),
        ),
        migrations.AddIndex(
            model_name='systemevent',
            index=models.Index(fields=['created_at'], name='system_even_created_01845d_idx'),
        ),
    ]
