# Generated by Django 6.0.6 on 2026-09-25 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0026_remove_campaign_task_alter_campaignaudience_customer_and_more'),
        ('events', '0003_systemevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemevent',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='campaigns.contact'),
        ),
        migrations.AlterField(
            model_name='systemevent',
            name='event_type',
            field=models.CharField(choices=[('WEBSITE', 'Website'), ('WEBHOOK', 'Webhook'), ('COMMUNICATION', 'Communication'), ('SYSTEM', 'System')], db_index=True, default='WEBSITE', max_length=20),
        ),
    ]
