# Generated by Django 6.0.6 on 2026-08-13 07:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaAdAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_id', models.CharField(help_text='Meta Ad Account ID', max_length=255, unique=True)),
                ('name', models.CharField(help_text='Name of the Ad Account', max_length=255)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('account_status', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_ad_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ads_meta_ad_accounts',
                'ordering': ['-created_at'],
            },
        ),
    ]
