# Generated by Django 6.0.6 on 2026-08-19 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_metausercredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='metausercredential',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metausercredential',
            name='meta_user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='metausercredential',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=20),
        ),
    ]
