# Generated by Django 6.0.6 on 2026-08-24 09:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_metaadaccount_amount_spent_metapixelsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaCapiEventLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_name', models.CharField(max_length=100)),
                ('pixel_id', models.CharField(max_length=255)),
                ('test_event_code', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='Success', max_length=50)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_capi_event_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ads_meta_capi_event_logs',
            },
        ),
    ]
