# Generated by Django 6.0.6 on 2026-08-17 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_alter_formfield_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='fields_schema',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='answers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='submissionanswer',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_answers', to='forms.formsubmission'),
        ),
    ]
