# Generated by Django 6.0.6 on 2026-08-17 10:06

from django.db import migrations


def migrate_forms_data(apps, schema_editor):
    Form = apps.get_model('forms', 'Form')
    FormField = apps.get_model('forms', 'FormField')
    FormSubmission = apps.get_model('forms', 'FormSubmission')
    SubmissionAnswer = apps.get_model('forms', 'SubmissionAnswer')

    # Migrate FormFields to fields_schema
    for form in Form.objects.all():
        fields = FormField.objects.filter(form=form).order_by('step_number', 'field_order')
        schema = []
        for field in fields:
            schema.append({
                'id': field.id,
                'step_number': field.step_number,
                'field_type': field.field_type,
                'label': field.label,
                'placeholder': field.placeholder,
                'help_text': field.help_text,
                'required': field.required,
                'unique_field': field.unique_field,
                'options': field.options,
                'validation_rules': field.validation_rules,
                'conditional_logic': field.conditional_logic,
                'settings': field.settings,
                'field_order': field.field_order
            })
        form.fields_schema = schema
        form.save(update_fields=['fields_schema'])

    # Migrate SubmissionAnswers to answers
    for submission in FormSubmission.objects.all():
        answers_qs = SubmissionAnswer.objects.filter(submission=submission)
        answers_dict = {}
        for answer in answers_qs:
            answers_dict[str(answer.field_id)] = answer.answer
        
        submission.answers = answers_dict
        submission.save(update_fields=['answers'])

def reverse_migrate_forms_data(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_form_fields_schema_formsubmission_answers_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_forms_data, reverse_migrate_forms_data),
    ]
