# Generated by Django 6.0.6 on 2026-08-17 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_auto_20260817_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissionanswer',
            name='field',
        ),
        migrations.RemoveField(
            model_name='submissionanswer',
            name='submission',
        ),
        migrations.DeleteModel(
            name='FormField',
        ),
        migrations.DeleteModel(
            name='SubmissionAnswer',
        ),
    ]
