"use client";

import { useMutation } from "@tanstack/react-query";
import { Check, ChevronLeft, ChevronRight, ImagePlus, X } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";
import { metaAdsService } from "@/services/meta-ads.service";
import { parseApiError } from "@/services/api-client";
import type { CreateMetaCampaignPayload, MetaAdAccount } from "@/types/meta-ads";

const objectives = ["OUTCOME_LEADS", "OUTCOME_TRAFFIC", "OUTCOME_AWARENESS", "OUTCOME_SALES"];
const categories = ["NONE", "CREDIT", "EMPLOYMENT", "HOUSING", "ISSUES_ELECTIONS_POLITICS"];

export function CampaignWizard({ account, onClose, onCreated }: { account: MetaAdAccount; onClose: () => void; onCreated?: () => void }) {
  const [step, setStep] = useState(1);
  const [imageName, setImageName] = useState("");
  const [form, setForm] = useState({ name: "", objective: "OUTCOME_LEADS", special_ad_categories: ["NONE"], daily_budget: "1000", start_time: "", end_time: "", location: "US", age_min: "18", age_max: "65", ad_text: "", call_to_action: "SIGN_UP", leadgen_form_id: "" });
  const update = (key: keyof typeof form, value: string | string[]) => setForm(current => ({ ...current, [key]: value }));
  const payload = useMemo<CreateMetaCampaignPayload>(() => ({ account_id: account.account_id, name: form.name, objective: form.objective, special_ad_categories: form.special_ad_categories, daily_budget: Math.round(Number(form.daily_budget) * 100), start_time: form.start_time || undefined, end_time: form.end_time || undefined, location: form.location, age_min: Number(form.age_min), age_max: Number(form.age_max), ad_text: form.ad_text, call_to_action: form.call_to_action, leadgen_form_id: form.leadgen_form_id || undefined }), [account.account_id, form]);
  const create = useMutation({ mutationFn: () => metaAdsService.createCampaign(payload), onSuccess: () => { toast.success("Campaign created as paused"); onCreated?.(); onClose(); }, onError: error => toast.error(parseApiError(error)) });
  const canProceed = step === 1 ? Boolean(form.name && form.objective) : step === 2 ? Number(form.daily_budget) > 0 && Boolean(form.location) : Boolean(form.ad_text);
  const toggleCategory = (category: string) => update("special_ad_categories", category === "NONE" ? ["NONE"] : [...form.special_ad_categories.filter(c => c !== "NONE" && c !== category), category]);

  return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4 backdrop-blur-sm">
    <section role="dialog" aria-modal="true" aria-labelledby="campaign-wizard-title" className="max-h-[92vh] w-full max-w-3xl overflow-y-auto rounded-3xl bg-white shadow-2xl">
      <header className="flex items-center justify-between border-b border-slate-100 px-6 py-5"><div><h2 id="campaign-wizard-title" className="text-xl font-black text-slate-900">Create Meta campaign</h2><p className="text-sm text-slate-500">{account.name} · saved as paused for review</p></div><button onClick={onClose} aria-label="Close" className="rounded-lg p-2 text-slate-400 hover:bg-slate-100"><X size={20}/></button></header>
      <div className="grid grid-cols-3 border-b border-slate-100 px-6">{["Campaign", "Ad set", "Creative"].map((label, index) => <div key={label} className={`flex items-center gap-2 border-b-2 py-4 text-sm font-bold ${step === index + 1 ? "border-blue-600 text-blue-700" : "border-transparent text-slate-400"}`}><span className={`grid h-6 w-6 place-items-center rounded-full text-xs ${step > index + 1 ? "bg-emerald-500 text-white" : step === index + 1 ? "bg-blue-600 text-white" : "bg-slate-100"}`}>{step > index + 1 ? <Check size={14}/> : index + 1}</span><span className="hidden sm:inline">{label}</span></div>)}</div>
      <div className="space-y-5 p-6">
        {step === 1 && <><Field label="Campaign name"><input value={form.name} onChange={e => update("name", e.target.value)} placeholder="e.g. Autumn lead generation" autoFocus /></Field><Field label="Objective"><select value={form.objective} onChange={e => update("objective", e.target.value)}>{objectives.map(item => <option key={item} value={item}>{item.replace("OUTCOME_", "")}</option>)}</select></Field><fieldset><legend className="mb-2 text-sm font-bold text-slate-700">Special ad categories</legend><div className="flex flex-wrap gap-2">{categories.map(category => <button type="button" key={category} onClick={() => toggleCategory(category)} className={`rounded-full border px-3 py-1.5 text-xs font-bold ${form.special_ad_categories.includes(category) ? "border-blue-600 bg-blue-50 text-blue-700" : "border-slate-200 text-slate-500"}`}>{category.replaceAll("_", " ")}</button>)}</div></fieldset></>}
        {step === 2 && <><div className="grid gap-4 sm:grid-cols-2"><Field label="Daily budget (account currency)"><input type="number" min="1" value={form.daily_budget} onChange={e => update("daily_budget", e.target.value)} /></Field><Field label="Location"><input value={form.location} onChange={e => update("location", e.target.value)} placeholder="US" /></Field><Field label="Start date"><input type="datetime-local" value={form.start_time} onChange={e => update("start_time", e.target.value)} /></Field><Field label="End date (optional)"><input type="datetime-local" value={form.end_time} onChange={e => update("end_time", e.target.value)} /></Field><Field label="Minimum age"><input type="number" min="18" value={form.age_min} onChange={e => update("age_min", e.target.value)} /></Field><Field label="Maximum age"><input type="number" max="65" value={form.age_max} onChange={e => update("age_max", e.target.value)} /></Field></div></>}
        {step === 3 && <><Field label="Creative image"><label className="flex cursor-pointer items-center justify-center gap-2 rounded-xl border border-dashed border-slate-300 bg-slate-50 px-4 py-7 text-sm font-semibold text-slate-500 hover:border-blue-400 hover:text-blue-600"><ImagePlus size={20}/>{imageName || "Choose image (upload integration supplies image_hash)"}<input className="sr-only" type="file" accept="image/*" onChange={e => setImageName(e.target.files?.[0]?.name ?? "")} /></label></Field><Field label="Ad copy"><textarea rows={4} value={form.ad_text} onChange={e => update("ad_text", e.target.value)} placeholder="Tell people why they should take action." /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Call to action"><select value={form.call_to_action} onChange={e => update("call_to_action", e.target.value)}><option>SIGN_UP</option><option>LEARN_MORE</option><option>CONTACT_US</option></select></Field><Field label="Lead form ID"><input value={form.leadgen_form_id} onChange={e => update("leadgen_form_id", e.target.value)} placeholder="Meta instant form ID" /></Field></div></>}
      </div>
      <footer className="flex items-center justify-between border-t border-slate-100 px-6 py-4"><button type="button" disabled={step === 1} onClick={() => setStep(s => s - 1)} className="flex items-center gap-1 rounded-xl px-3 py-2 text-sm font-bold text-slate-600 disabled:invisible"><ChevronLeft size={17}/>Back</button>{step < 3 ? <button type="button" disabled={!canProceed} onClick={() => setStep(s => s + 1)} className="flex items-center gap-1 rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50">Continue<ChevronRight size={17}/></button> : <button type="button" disabled={!canProceed || create.isPending} onClick={() => create.mutate()} className="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50">{create.isPending ? "Creating…" : "Create campaign"}</button>}</footer>
    </section>
  </div>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="grid gap-1.5 text-sm font-bold text-slate-700"><span>{label}</span><span className="[&_input]:w-full [&_input]:rounded-xl [&_input]:border [&_input]:border-slate-200 [&_input]:px-3 [&_input]:py-2.5 [&_select]:w-full [&_select]:rounded-xl [&_select]:border [&_select]:border-slate-200 [&_select]:bg-white [&_select]:px-3 [&_select]:py-2.5 [&_textarea]:w-full [&_textarea]:rounded-xl [&_textarea]:border [&_textarea]:border-slate-200 [&_textarea]:p-3">{children}</span></label>; }
