# Generated by Django 6.0.6 on 2026-08-17 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='webhookevent',
            name='webhook_eve_secret_b40d12_idx',
        ),
        migrations.RemoveIndex(
            model_name='webhookevent',
            name='webhook_eve_created_9addbf_idx',
        ),
        migrations.DeleteModel(
            name='WebhookEvent',
        ),
    ]
