# Generated by Django 6.0.6 on 2026-09-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_refactor_role_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mauser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('USER', 'User')], default='USER', max_length=20),
        ),
    ]
