# Generated by Django 6.0.6 on 2026-09-13 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_mauser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mauser',
            name='managed_by',
        ),
    ]
