# Generated by Django 6.0.6 on 2026-08-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_automationexecution_paused_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='workflow_graph',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
