# Generated by Django 6.0.6 on 2026-08-17 10:33

from django.db import migrations


def migrate_graph_data(apps, schema_editor):
    Automation = apps.get_model('automation', 'Automation')
    AutomationNode = apps.get_model('automation', 'AutomationNode')
    AutomationEdge = apps.get_model('automation', 'AutomationEdge')
    
    for automation in Automation.objects.all():
        nodes = []
        for node in AutomationNode.objects.filter(automation_id=automation.id):
            nodes.append({
                "id": str(node.id),
                "type": node.node_type,
                "action_name": node.action_name,
                "label": node.label,
                "business_config": node.business_config,
                "ui_config": node.ui_config,
                "execution_order": node.execution_order
            })
            
        edges = []
        for edge in AutomationEdge.objects.filter(automation_id=automation.id):
            edges.append({
                "id": str(edge.id),
                "source": str(edge.source_node_id),
                "target": str(edge.target_node_id),
                "edge_type": edge.edge_type
            })
            
        automation.workflow_graph = {
            "nodes": nodes,
            "edges": edges
        }
        automation.save(update_fields=['workflow_graph'])

class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0004_automation_workflow_graph'),
    ]

    operations = [
        migrations.RunPython(migrate_graph_data, reverse_code=migrations.RunPython.noop),
    ]
