# Generated by Django 6.0.6 on 2026-08-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0005_auto_20260817_1603'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='automationedge',
            name='automation__automat_c87188_idx',
        ),
        migrations.RemoveIndex(
            model_name='automationedge',
            name='automation__source__e4d1fe_idx',
        ),
        migrations.RemoveIndex(
            model_name='automationedge',
            name='automation__target__44bbda_idx',
        ),
        migrations.RemoveIndex(
            model_name='automationnode',
            name='automation__automat_f55a51_idx',
        ),
        migrations.RemoveIndex(
            model_name='automationnode',
            name='automation__node_ty_38eaf6_idx',
        ),
        migrations.RemoveIndex(
            model_name='automationnode',
            name='automation__action__dbd189_idx',
        ),
        migrations.AlterField(
            model_name='automationexecution',
            name='current_node',
            field=models.CharField(blank=True, max_length=255, null=True, db_column='current_node_id'),
        ),
        migrations.RenameField(
            model_name='automationexecution',
            old_name='current_node',
            new_name='current_node_id',
        ),
        migrations.AlterField(
            model_name='automationexecution',
            name='current_node_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveIndex(
            model_name='automationexecutionlog',
            name='automation__node_id_769588_idx',
        ),
        migrations.AlterField(
            model_name='automationexecutionlog',
            name='node',
            field=models.CharField(blank=True, max_length=255, null=True, db_column='node_id'),
        ),
        migrations.RenameField(
            model_name='automationexecutionlog',
            old_name='node',
            new_name='node_id',
        ),
        migrations.AlterField(
            model_name='automationexecutionlog',
            name='node_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='automationexecutionlog',
            index=models.Index(fields=['node_id'], name='automation__node_id_769588_idx'),
        ),
        migrations.RemoveField(
            model_name='automationnode',
            name='automation',
        ),
        migrations.DeleteModel(
            name='AutomationEdge',
        ),
        migrations.DeleteModel(
            name='AutomationNode',
        ),
    ]
