# Generated by Django 6.0.6 on 2026-09-29 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0007_routingrule_workflowaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowaction',
            name='rule',
        ),
        migrations.DeleteModel(
            name='RoutingRule',
        ),
        migrations.DeleteModel(
            name='WorkflowAction',
        ),
    ]
