# Generated by Django 6.0.6 on 2026-08-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_migrate_social_connections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationprovider',
            name='provider_type',
            field=models.CharField(choices=[('OPENAI', 'OpenAI'), ('AWS_S3', 'AWS S3'), ('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('LINKEDIN', 'LinkedIn'), ('X', 'X (Twitter)'), ('SMTP', 'SMTP'), ('AWS_SES', 'Amazon SES'), ('MSG91', 'MSG91'), ('META_WHATSAPP', 'Meta WhatsApp Business Platform'), ('FCM', 'Firebase Cloud Messaging'), ('VAPID', 'Web Push (VAPID)')], db_index=True, max_length=20, unique=True),
        ),
    ]
