# Generated by Django 6.0.6 on 2026-08-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_library', '0004_alter_assettag_unique_together_remove_asset_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='folder',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='tags',
        ),
        migrations.AddField(
            model_name='asset',
            name='path',
            field=models.CharField(db_index=True, default='/', help_text='Virtual folder path, e.g. /images/campaign2024/', max_length=1024),
        ),
        migrations.DeleteModel(
            name='AssetFolder',
        ),
        migrations.DeleteModel(
            name='AssetTag',
        ),
        migrations.AddField(
            model_name='asset',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='List of string tags'),
        ),
    ]
