# Generated by Django 6.0.6 on 2026-08-17 10:54

from django.db import migrations

def migrate_providers(apps, schema_editor):
    IntegrationProvider = apps.get_model("integrations", "IntegrationProvider")

    # Migrate Email Providers
    EmailProvider = apps.get_model("communications", "OrganizationEmailProvider")
    for ep in EmailProvider.objects.all():
        IntegrationProvider.objects.create(
            provider_type=ep.provider,
            is_active=ep.is_active,
            credentials={
                "aws_access_key": ep.aws_access_key,
                "aws_secret_key": ep.aws_secret_key,
                "aws_region": ep.aws_region,
                "verified_domain": ep.verified_domain,
                "daily_limit": ep.daily_limit,
                "monthly_limit": ep.monthly_limit,
            }
        )

    # Migrate SMS Providers
    SMSProvider = apps.get_model("communications", "OrganizationSMSProvider")
    for sp in SMSProvider.objects.all():
        IntegrationProvider.objects.create(
            provider_type=sp.provider,
            is_active=sp.is_active,
            credentials={
                "auth_key": sp.auth_key,
                "sender_id": sp.sender_id,
            }
        )

    # Migrate WhatsApp Providers
    WAProvider = apps.get_model("communications", "OrganizationWhatsAppProvider")
    for wap in WAProvider.objects.all():
        # Map META to META_WHATSAPP
        ptype = "META_WHATSAPP" if wap.provider == "META" else wap.provider
        IntegrationProvider.objects.create(
            provider_type=ptype,
            is_active=wap.is_active,
            credentials={
                "access_token": wap.access_token,
                "phone_number_id": wap.phone_number_id,
                "business_account_id": wap.business_account_id,
            }
        )

    # Migrate Push Providers
    PushProvider = apps.get_model("communications", "OrganizationPushProvider")
    for pp in PushProvider.objects.all():
        IntegrationProvider.objects.create(
            provider_type=pp.provider,
            is_active=pp.is_active,
            credentials={
                "server_key": pp.server_key,
            }
        )


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_remove_communicationevent_communicati_organiz_9b5bcd_idx_and_more'),
        ('integrations', '0006_alter_integrationprovider_provider_type'),
    ]

    operations = [
        migrations.RunPython(migrate_providers, migrations.RunPython.noop),
    ]
