# Generated by Django 6.0.6 on 2026-08-17 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0004_auto_20260817_1624'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='organizationemailprovider',
            name='organizatio_provide_17f674_idx',
        ),
        migrations.RemoveIndex(
            model_name='organizationemailprovider',
            name='organizatio_is_acti_882146_idx',
        ),
        migrations.DeleteModel(
            name='OrganizationEmailProvider',
        ),
        migrations.RemoveIndex(
            model_name='organizationpushprovider',
            name='organizatio_provide_834c35_idx',
        ),
        migrations.RemoveIndex(
            model_name='organizationpushprovider',
            name='organizatio_is_acti_19de2e_idx',
        ),
        migrations.DeleteModel(
            name='OrganizationPushProvider',
        ),
        migrations.RemoveIndex(
            model_name='organizationsmsprovider',
            name='organizatio_provide_fa1afd_idx',
        ),
        migrations.RemoveIndex(
            model_name='organizationsmsprovider',
            name='organizatio_is_acti_2fa14c_idx',
        ),
        migrations.DeleteModel(
            name='OrganizationSMSProvider',
        ),
        migrations.RemoveIndex(
            model_name='organizationwhatsappprovider',
            name='organizatio_provide_098536_idx',
        ),
        migrations.RemoveIndex(
            model_name='organizationwhatsappprovider',
            name='organizatio_is_acti_7a69dd_idx',
        ),
        migrations.DeleteModel(
            name='OrganizationWhatsAppProvider',
        ),
    ]
