# Generated by Django 6.0.6 on 2026-09-11 05:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0005_remove_organizationemailprovider_organizatio_provide_17f674_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SenderIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('provider', models.CharField(choices=[('GMAIL', 'Gmail'), ('MICROSOFT', 'Microsoft Outlook'), ('YAHOO', 'Yahoo'), ('CUSTOM_SMTP', 'Custom SMTP')], max_length=30)),
                ('connection_type', models.CharField(choices=[('OAUTH', 'OAuth 2.0'), ('SMTP', 'SMTP')], max_length=30)),
                ('status', models.CharField(choices=[('CONNECTED', 'Connected'), ('NOT_CONNECTED', 'Not Connected'), ('FAILED', 'Connection Failed'), ('RECONNECT_REQUIRED', 'Reconnect Required')], default='CONNECTED', max_length=30)),
                ('encrypted_credentials', models.JSONField(blank=True, default=dict)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sender_identity',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'provider'], name='sender_iden_user_id_37f99e_idx'), models.Index(fields=['email'], name='sender_iden_email_08569d_idx')],
            },
        ),
    ]
