# Generated by Django 6.0.6 on 2026-09-24 08:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0005_remove_organizationemailprovider_organizatio_provide_17f674_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number_id', models.CharField(db_index=True, help_text='Meta WhatsApp Phone Number ID', max_length=100)),
                ('encrypted_access_token', models.TextField(help_text='Encrypted Meta WhatsApp Access Token')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'whatsapp_connection',
            },
        ),
        migrations.AddField(
            model_name='communicationevent',
            name='whatsapp_connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_events', to='communications.whatsappconnection'),
        ),
        migrations.AddIndex(
            model_name='whatsappconnection',
            index=models.Index(fields=['organization', 'is_active'], name='whatsapp_co_organiz_862732_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappconnection',
            index=models.Index(fields=['phone_number_id'], name='whatsapp_co_phone_n_a3eb97_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='whatsappconnection',
            unique_together={('organization', 'phone_number_id')},
        ),
    ]
