# Generated by Django 6.0.6 on 2026-09-14 11:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0006_senderidentity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='senderidentity',
            name='account_review_status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='senderidentity',
            name='business_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='senderidentity',
            name='code_verification_status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='senderidentity',
            name='phone_number_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='senderidentity',
            name='quality_rating',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='senderidentity',
            name='verified_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='senderidentity',
            name='waba_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='communicationevent',
            name='status',
            field=models.CharField(choices=[('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('OPENED', 'Opened'), ('CLICKED', 'Clicked'), ('READ', 'Read'), ('REPLIED', 'Replied'), ('RECEIVED', 'Received'), ('BOUNCED', 'Bounced'), ('UNSUBSCRIBED', 'Unsubscribed'), ('FAILED', 'Failed')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='senderidentity',
            name='connection_type',
            field=models.CharField(choices=[('OAUTH', 'OAuth 2.0'), ('SMTP', 'SMTP'), ('API_KEY', 'API Key / Token')], max_length=30),
        ),
        migrations.AlterField(
            model_name='senderidentity',
            name='provider',
            field=models.CharField(choices=[('GMAIL', 'Gmail'), ('MICROSOFT', 'Microsoft Outlook'), ('YAHOO', 'Yahoo'), ('CUSTOM_SMTP', 'Custom SMTP'), ('WHATSAPP_CLOUD', 'WhatsApp Cloud API'), ('TWILIO_SMS', 'Twilio SMS'), ('CUSTOM_SMS', 'Custom SMS Gateway')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='senderidentity',
            index=models.Index(fields=['phone_number_id'], name='sender_iden_phone_n_a7dfbe_idx'),
        ),
        migrations.AddIndex(
            model_name='senderidentity',
            index=models.Index(fields=['waba_id'], name='sender_iden_waba_id_06d34f_idx'),
        ),
    ]
