# Generated by Django 6.0.6 on 2026-09-21 12:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0007_senderidentity_account_review_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainAuthentication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(db_index=True, max_length=255)),
                ('verification_token', models.CharField(max_length=100)),
                ('dns_record_type', models.CharField(default='TXT', max_length=10)),
                ('dns_record_name', models.CharField(default='@', max_length=50)),
                ('dns_record_value', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('FAILED', 'Verification Failed')], db_index=True, default='PENDING', max_length=30)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_authentications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'domain_authentication',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='senderidentity',
            name='domain_auth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender_identities', to='communications.domainauthentication'),
        ),
        migrations.AddIndex(
            model_name='domainauthentication',
            index=models.Index(fields=['user', 'status'], name='domain_auth_user_id_adb857_idx'),
        ),
        migrations.AddIndex(
            model_name='domainauthentication',
            index=models.Index(fields=['domain'], name='domain_auth_domain_6405fa_idx'),
        ),
        migrations.AddConstraint(
            model_name='domainauthentication',
            constraint=models.UniqueConstraint(fields=('domain',), name='unique_domain_global'),
        ),
    ]
