# Generated by Django 6.0.6 on 2026-09-28 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0006_whatsappconnection_and_more'),
        ('communications', '0008_domainauthentication_senderidentity_domain_auth_and_more'),
    ]

    operations = [
    ]
