# Generated by Django 6.0.6 on 2026-09-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0009_merge_20260928_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainauthentication',
            name='dkim_records',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='domainauthentication',
            name='dkim_status',
            field=models.CharField(default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='domainauthentication',
            name='mail_from_domain',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='senderidentity',
            name='connection_type',
            field=models.CharField(choices=[('AWS_SES', 'Amazon SES'), ('SMTP', 'SMTP'), ('API_KEY', 'API Key / Token')], max_length=30),
        ),
        migrations.AlterField(
            model_name='senderidentity',
            name='provider',
            field=models.CharField(choices=[('AWS_SES', 'Amazon SES (Verified Domain)'), ('CUSTOM_SMTP', 'Custom SMTP'), ('WHATSAPP_CLOUD', 'WhatsApp Cloud API'), ('TWILIO_SMS', 'Twilio SMS'), ('CUSTOM_SMS', 'Custom SMS Gateway')], max_length=30),
        ),
    ]
